import { create } from "zustand";

export const useAssetsStore = create((set, get) => ({
  AssetList: [
    // CRYPTO
    {
      id: 1,
      name: "ETH/USD",
      type: "Crypto",
      symbol: "cryETHUSD",
      historySymbol: "ETHUSDT",
      avatar: "https://api.testtrademo.com/uploads/logo/ETHUSD.png",
    },
    {
      id: 2,
      name: "BTC/USD",
      type: "Crypto",
      symbol: "cryBTCUSD",
      historySymbol: "BTCUSDT",
      avatar: "https://api.testtrademo.com/uploads/logo/BTCUSD.png",
    },
    // Forex
    {
      id: 3,
      name: "GBP/USD",
      type: "Forex",
      symbol: "frxGBPUSD",
      historySymbol: "GBPUSD=X",
      avatar: "https://api.testtrademo.com/uploads/logo/GBPUSD.png",
    },
    {
      id: 4,
      name: "EUR/USD",
      type: "Forex",
      symbol: "frxEURUSD",
      historySymbol: "EURUSD=X",
      avatar: "https://api.testtrademo.com/uploads/logo/EURUSD.png",
    },
    {
      id: 5,
      name: "EUR/JPY",
      type: "Forex",
      symbol: "frxEURJPY",
      historySymbol: "EURJPY=X",
      avatar: "https://api.testtrademo.com/uploads/logo/EURUSD.png",
    },
    {
      id: 6,
      name: "USD/JPY",
      type: "Forex",
      symbol: "frxUSDJPY",
      historySymbol: "USDJPY=X",
      avatar: "https://api.testtrademo.com/uploads/logo/USDJPY.png",
    },
    {
      id: 7,
      name: "AUD/USD",
      type: "Forex",
      symbol: "frxAUDUSD",
      historySymbol: "AUDUSD=X",
      avatar: "https://api.testtrademo.com/uploads/logo/AUDUSD.png",
    },
    {
      id: 8,
      name: "USD/CAD",
      type: "Forex",
      symbol: "frxUSDCAD",
      historySymbol: "USDCAD=X",
      avatar: "https://api.testtrademo.com/uploads/logo/USDCAD.png",
    },
    {
      id: 9,
      name: "USD/CHF",
      type: "Forex",
      symbol: "frxUSDCHF",
      historySymbol: "USDCHF=X",
      avatar: "https://api.testtrademo.com/uploads/logo/USDCHF.png",
    },
    {
      id: 10,
      name: "NZD/USD",
      type: "Forex",
      symbol: "frxNZDUSD",
      historySymbol: "NZDUSD=X",
      avatar: "https://api.testtrademo.com/uploads/logo/NZDUSD.png",
    },
    {
      id: 11,
      name: "EUR/GBP",
      type: "Forex",
      symbol: "frxEURGBP",
      historySymbol: "EURGBP=X",
      avatar: "https://api.testtrademo.com/uploads/logo/EURGBP.png",
    },
    {
      id: 12,
      name: "EUR/AUD",
      type: "Forex",
      symbol: "frxEURAUD",
      historySymbol: "EURAUD=X",
      avatar: "https://api.testtrademo.com/uploads/logo/EURAUD.png",
    },
    {
      id: 13,
      name: "GBP/JPY",
      type: "Forex",
      symbol: "frxGBPJPY",
      historySymbol: "GBPJPY=X",
      avatar: "https://api.testtrademo.com/uploads/logo/GBPJPY.png",
    },
    {
      id: 14,
      name: "AUD/JPY",
      type: "Forex",
      symbol: "frxAUDJPY",
      historySymbol: "AUDJPY=X",
      avatar: "https://api.testtrademo.com/uploads/logo/AUDJPY.png",
    },
    {
      id: 15,
      name: "EUR/CAD",
      type: "Forex",
      symbol: "frxEURCAD",
      historySymbol: "EURCAD=X",
      avatar: "https://api.testtrademo.com/uploads/logo/EURCAD.png",
    },
    {
      id: 16,
      name: "GBP/AUD",
      type: "Forex",
      symbol: "frxGBPAUD",
      historySymbol: "GBPAUD=X",
      avatar: "https://api.testtrademo.com/uploads/logo/GBPAUD.png",
    },
    //Metals
    {
      id: 17,
      name: "XAU/USD",
      type: "Metals",
      symbol: "frxXAUUSD",
      historySymbol: "GC=F",
      avatar: "https://api.testtrademo.com/uploads/logo/XAUUSD.png",
    },
    {
      id: 18,
      name: "XAG/USD",
      type: "Metals",
      symbol: "frxXAGUSD",
      historySymbol: "SI=F",
      avatar: "https://api.testtrademo.com/uploads/logo/XAGUSD.png",
    },
    // CFD
    {
      id: 19,
      name: "US 500",
      type: "CFD",
      symbol: "OTC_SPC",
      historySymbol: "%5EGSPC",
      avatar: "https://api.testtrademo.com/uploads/logo/USDX.png",
    },
    {
      id: 20,
      name: "Germany 40",
      type: "CFD",
      symbol: "OTC_GDAXI",
      historySymbol: "%5EGDAXI",
      avatar: "https://api.testtrademo.com/uploads/logo/USDX.png",
    },
    {
      id: 21,
      name: "UK 100",
      type: "CFD",
      symbol: "OTC_FTSE",
      historySymbol: "%5EFTSE",
      avatar: "https://api.testtrademo.com/uploads/logo/USDX.png",
    },
    {
      id: 22,
      name: "Japan 225",
      type: "CFD",
      symbol: "OTC_N225",
      historySymbol: "%5EN225",
      avatar: "https://api.testtrademo.com/uploads/logo/USDX.png",
    },
  ],
  selectedAsset: {
    id: 2,
    name: "BTC/USD",
    type: "Crypto",
    symbol: "cryBTCUSD",
    historySymbol: "BTCUSDT",
    avatar: "https://api.testtrademo.com/uploads/logo/BTCUSD.png",
  },
  setSellectedAssetById: (id) => {
    const asset = get().AssetList.find((asset) => asset.id === id);
    set({ selectedAsset: asset });
  },
  getAssetBySymbol: (symbol) => {
    return get().AssetList.find((asset) => asset.symbol === symbol);
  },
  //   setAssetList: (data) => set({ AssetList: data }),
}));
